service: playlist-builder

frameworkVersion: '2'

provider:
  region: "eu-west-1"
  name: aws
  runtime: go1.x
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "xray:*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

custom:
  - serverless-jetpack

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  playlists:
    handler: bin/playlists
    environment:
      TABLE_NAME: "example-playlists"
    events:
      - http:
          path: /playlists
          method: ANY
          cors: true
      - http:
          path: /playlists/{id}
          method: ANY
          cors: true
  profile:
    handler: bin/profile
    environment:
      TABLE_NAME: "profiles"
    events:
      - http:
          path: /profile
          method: ANY
          cors: true
      - http:
          path: /profile/{id}
          method: ANY
          cors: true
# Cloudformation for databases
resources:
  - ${file(./playlists/serverless/dynamodb_playlist_table.yml)}
  - ${file(./profile/serverless/dynamodb_profile_table.yml)}
plugins:
  - serverless-offline
